# Generated by Django 4.0.4 on 2022-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
