# Generated by Django 4.0.4 on 2022-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='uploaded_file',
            field=models.FileField(default='ggwp', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
