# Generated by Django 4.0.4 on 2022-07-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_answer_image_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answerImage',
            field=models.ImageField(blank=True, upload_to='answer/images/'),
        ),
        migrations.AlterField(
            model_name='system',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='course.subject'),
        ),
    ]
