# Generated by Django 4.0.4 on 2022-07-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0010_bear_cat_dog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'course'), ('model', 'bear')), models.Q(('app_label', 'course'), ('model', 'cat')), models.Q(('app_label', 'course'), ('model', 'dog')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
