# Generated by Django 4.0.4 on 2022-07-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_delete_bear_delete_cat_delete_dog_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='system',
            new_name='name',
        ),
        migrations.AddField(
            model_name='system',
            name='sub_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.system'),
        ),
    ]
