# Generated by Django 4.0.4 on 2022-07-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_rename_system_system_name_system_sub_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='name',
            new_name='system',
        ),
        migrations.RemoveField(
            model_name='system',
            name='sub_system',
        ),
    ]
