# Generated by Django 4.0.4 on 2022-07-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_generatetest_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatetest',
            name='user',
        ),
    ]
