# Generated by Django 4.0.4 on 2022-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_generatetest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaination_image',
            field=models.ImageField(blank=True, upload_to='question/images/explanation/'),
        ),
    ]
