# Generated by Django 4.0.4 on 2022-07-28 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_generatetest_completion_status_generatetest_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuserquestionanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='is_unused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userquestion',
            unique_together={('user', 'question')},
        ),
    ]
