# Generated by Django 4.0.4 on 2022-07-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0019_tempuserquestionanswer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tempuserquestionanswer',
            unique_together={('test', 'question')},
        ),
        migrations.CreateModel(
            name='TimeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.generatetest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
