# Generated by Django 4.0.4 on 2022-07-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_tempuserquestionanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetrack',
            old_name='time_taken',
            new_name='time_taken_till',
        ),
    ]
