# Generated by Django 4.0.4 on 2022-07-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_rename_time_taken_timetrack_time_taken_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_incorrect',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_marked',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_unused',
        ),
    ]
