# Generated by Django 4.0.4 on 2022-08-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_remove_answer_answerimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
    ]
