# Generated by Django 4.0.4 on 2022-08-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_remove_question_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.system'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.topic'),
        ),
    ]
