# Generated by Django 4.0.4 on 2022-08-10 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0027_alter_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestion',
            name='is_incorrect',
        ),
        migrations.AddField(
            model_name='generatetest',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatetest',
            name='total_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatetest',
            name='total_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questiontest',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questiontest',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timed', models.BooleanField(default=False)),
                ('tutor', models.BooleanField(default=False)),
                ('total_question', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_incorrect', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
