# Generated by Django 4.0.4 on 2022-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_remove_userquestion_is_incorrect_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
