# Generated by Django 4.0.4 on 2022-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_delete_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatetest',
            name='status',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
