# Generated by Django 4.0.4 on 2022-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_generatetest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontest',
            name='is_omitted',
            field=models.BooleanField(default=True),
        ),
    ]
