# Generated by Django 4.0.4 on 2022-08-12 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0031_questiontest_is_omitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetest',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='CIStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_to_i', models.IntegerField(default=0)),
                ('i_to_c', models.IntegerField(default=0)),
                ('i_to_i', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
