# Generated by Django 4.0.4 on 2022-08-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_alter_generatetest_score_cistat'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontest',
            name='submitted_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='course.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='explainationText',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.TextField(max_length=150),
        ),
    ]
